package ua.knu.knudev.knudevcommon.constant;

public enum FilterOptions {
    USER_INITIALS_AND_EMAIL,
    REGISTRATION_DATE,
    REGISTRATION_DATE_END_TIME,
    KNUDEV_UNIT,
    EXPERTISE,
    DEPARTMENT,
    SPECIALTY,
    UNIVERSITY_STUDY_YEAR,
    RECRUITMENT_NUMBER,
    TECHNICAL_ROLE
}
