package ua.knu.knudev.knudevcommon.constant;

public enum RolePromotionConditionSignature {
    PROJECTS_COUNT_KEY_CONSTANT,
    COMMITS_COUNT_KEY_CONSTANT,
    CREATED_TASKS_IN_CAMPUS_AMOUNT_KEY_CONSTANT,
    MENTORED_SESSIONS_AMOUNT_KEY_CONSTANT,
    WAS_A_SUPERVISOR_KEY_CONSTANT,
    WAS_AN_ARCHITECT_KEY_CONSTANT
}

